### ISSUE TITLE
Add reverse cycling  #enhancement 

### ISSUE THREAD

**Issue by icr1001** [phibr0/cycle-through-panes#1]
Thanks for this plugin!
It can be improved by having a reverse cycling command with "Ctrl + Shift +Tab"

**Comment by phibr0** [comment]
I will look into that

**Comment by phibr0** [comment]
Pushed new Release with that Feature!

**Comment by icr1001** [comment]
> Pushed new Release with that Feature!

Thank you @phibr0 😃
