### ISSUE TITLE
Plugin does not recognize excalidraw panes....

### ISSUE THREAD

**Issue by friklik** [phibr0/cycle-through-panes#11]
.... and does not cycle throught them.

**Comment by phibr0** [comment]
The Plugin ignores Panes that are not Markdown, but I am currently investigating a Solution so that you can add and remove Pane Types to switch to.

**Comment by phibr0** [comment]
The Plugin now has a Setting Tab where you can add and remove Panes. There are also two new Commands to help if you dont know the View Type.
