### ISSUE TITLE
Possible to Ctrl-tab to the default "empty" page

### ISSUE THREAD

**Issue by RobColes** [phibr0/cycle-through-panes#12]
Ctrl-tab works great to regular pages, but won't Ctrl-tab to the default "Empty" page.  It would be great to be able to Ctrl-tab to this, mostly to allow it to be closed from the keyboard. The "No file is open" page in the screenshot.

![Ctrl-Tab to empty page issue](https://user-images.githubusercontent.com/1765065/150678611-12a888a0-35df-4e43-b47d-4b56eb5aa662.png)

**Comment by Vinzent03** [comment]
There is a setting since v0.0.11. You can either open the settings and add a new line to the text field with  `empty` or focus the empty pane and call the command `Enable this view type`.

**Comment by RobColes** [comment]
That worked perfectly - thank you! Sorry I missed this.

**Comment by Vinzent03** [comment]
No problem. Happy to help.
