### ISSUE TITLE
I love the idea, but it's not working for me.

### ISSUE THREAD

**Issue by Newman5** [phibr0/cycle-through-panes#13]
I've enable / disabled the plugin and restarted Obsidian.  I'll try to uninstall and reinstall.  What else can I do?

**Comment by Vinzent03** [comment]
Some more information about what your pane setup looks like and what commands/hotkeys you use it helpful Is there any error in the console `CTRL + SHIFT + I`?

**Comment by Newman5** [comment]
Thanks for the speedy response!  Okay.  I'll record a video in a second, but first... CRTL + Shift + I is a custom hotkey for me.  It brings up the template modal.  I looked in the command pallet for console, found nothing.  But here is the debug info:
SYSTEM INFO:
	Obsidian version: v0.13.19
	Installer version: v0.10.13
	Login status: not logged in
	Insider build toggle: off
	Live preview: off
	Legacy editor: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 0
	Safe mode: off
	Plugins installed: 10
	Plugins enabled: 8
		1: Calendar
		2: Periodic Notes
		3: Remember cursor position
		4: Cycle through Panes
		5: Templater
		6: Dataview
		7: Outliner
		8: Excalidraw

RECOMMENDATIONS:
	Update installer: installer version too low, please download from https://obsidian.md/download and reinstall.
	Community plugins: for bugs, please try to make the issue happen in the help vault or disable community plugins.

So, I'll try to update the installer.  But first make a video showing the issue.

**Comment by Vinzent03** [comment]
I would definitely update the installer version before the video recording, because it may fix the issue and a video isn't needed anymore. To open the console remove the template hotkey temporary.

**Comment by Newman5** [comment]
I updated the installer and no joy (didn't fix the problem).  The video didnt really show anything.  Just when I Crtl+Tab, nothing happens.  I uninstall and reinstall the plugin and that doesn't fix.  

do I have a hot key for Crtl +Tab?  yes, it shows the plugin hotkeys.  I deleted them and re-did the crtl+tab.  still not working

oh well - thanks for your help!

**Comment by Vinzent03** [comment]
Please try opening two markdown files and call the command "Cycle through panes" manually via the command palette.

**Comment by Newman5** [comment]
Ah!  I got it to work.  Thank you for your help.  The reason why it "didn't work" was that I didn't have multiple markdown files open.  I thought it would cycle thru my recent files.  And, I realize this is silly now.  I though they were open but not visible.  My bad.  Thanks for all the help.  cheers.  Issue closed.
