### ISSUE TITLE
Doesn't cycle through panes in v1.0.3

### ISSUE THREAD

**Issue by serpro69** [phibr0/cycle-through-panes#15]
Seems like plugin stopped working (after version 1.0.0? )
I have two panes saved (calendar and kanban), but neither the shortcut nor running the command from the command-palette seems to be cycling through them.

**Comment by Vinzent03** [comment]
Where you you have these panes? In the sidebar or in the root like any other tab?

**Comment by serpro69** [comment]
They're in sidebars

**Comment by Vinzent03** [comment]
I don't think we supported sidebars before the update to 1.0.0. I see in the code that we actively ignore them, and I think that's good.

**Comment by serpro69** [comment]
Right, hmm.
I thought it did work for me at one point, but maybe I'm mistaken about how it actually worked.
Thanks for the info @Vinzent03 , closing this issue.
