### ISSUE TITLE
[Feature Request] Support for .CANVAS files

### ISSUE THREAD

**Issue by FelipeRearden** [phibr0/cycle-through-panes#16]
Hello @phibr0  and @Vinzent03 !!!!

This FR is simple to explain: would be amazing if this plugin add support for the new `.canvas` files when we are cycle between markdown files 😀

I hope you like my idea 🙏

I wish you a fantastic day ☀️

**Comment by Vinzent03** [comment]
What specific functionality are you using of this plugin? I'm thinking about whether this plugin still has a real benefit or not. Aren't all commands now in Obsidian itself, since 1.0.0?

**Comment by FelipeRearden** [comment]
Hello again @Vinzent03 !!!!

> What specific functionality are you using of this plugin? I'm thinking about whether this plugin still has a real benefit or not. Aren't all commands now in Obsidian itself, since 1.0.0?

Thats a great question and your plugin does something that we **dont** have in Obsidian until now :)

🐚 In a nutshell: the native  commands `go to next tab` and `go to previous tab` does not include the cases where we have **two split panes**. It only cycles between one of the panes.

Our beloved **Cycle Throught Panes**  cycles **all tabs in the workspace** 🏅🏅🏅

📸This is a typical workspace 
![3E5E0BA8-8F07-40CD-A6F7-C8B73872A8E2](https://user-images.githubusercontent.com/85180696/221362115-cf7d3dc7-c4cb-4ec3-89d0-ef1268053238.jpeg)

As you can see I have to split panes with 2 tabs in the left and 3 tabs in the right 

📹 This is **Cycle Throught Panes** 


![video](https://user-images.githubusercontent.com/85180696/221362287-483b8660-ee88-43fa-8070-26a23d4568d5.MOV)



📹 This is Obsidian Native Command → Only cycle between ONE SPLIT pane :(

![video](https://user-images.githubusercontent.com/85180696/221362391-1534c942-e868-4f30-be01-44af9e430103.MOV)

---

You are always creating plugins that are important for our Obsidian lives @Vinzent03 . No matter how old they are, we cant live without them :)

Thanks for your amazing work you are a legend @Vinzent03

**Comment by Vinzent03** [comment]
Thanks for the great demonstration. We both forgot our own feature xD. You can already change that yourself in the plugin's settings. Just add `canvas` in a new line.

**Comment by Vinzent03** [comment]
I've added it now as default view type as well. 1ad29f1

**Comment by FelipeRearden** [comment]
> Thanks for the great demonstration. 

Thanks for the feedback @Vinzent03 !!! I really appreciate 

> We both forgot our own feature xD. You can already change that yourself in the plugin's settings. Just add `canvas` in a new line.

OMG !!!! You are right, how could I forget to check the Settings😀

Thanks for telling me this !!! 

> I've added it now as default view type as well.

Working perfect on version 1.1.0 on Obsidian 1.1.15.

As always, thank you very much @Vinzent03 !!!!

Have a great day ☀️
