### ISSUE TITLE
[Feature Request] thumbnail of tabs when switching

### ISSUE THREAD

**Issue by dlccyes** [phibr0/cycle-through-panes#17]
In most browsers, when you press `ctrl+tab` and hold `ctrl`, a small popup window showing the thumbnails of the recent tabs will appear. It would be really nice if this plugin implements that!

**Comment by Vinzent03** [comment]
I've done it a bit differently. Much more like it's done in vscode. I wouldn't know how to implement that like in a browser, so I reused the existing available modal.

**Comment by dlccyes** [comment]
Thanks the modal works, but it seems to have broken https://github.com/phibr0/cycle-through-panes/issues/8? Holding `ctrl` and pressing `tab` no longer iterate through recently used tabs.

**Comment by Vinzent03** [comment]
But does it go through each item in the modal? When closing the modal is should navigate to the last focused item.

**Comment by dlccyes** [comment]
No? I can only switch to the most recent one. When I press `tab`, it does not go through each item in the modal as in VsCode.

**Comment by Vinzent03** [comment]
Ah, I had to change something in this area. I'm not really familiar with the exact keys on a Mac device, but it's not actually Ctrl which you are pressing, right? Which key are you pressing?

**Comment by dlccyes** [comment]
It is `control` I'm pressing. But isn't that up to user's own hotkey settings?

<img width="784" alt="image" src="https://user-images.githubusercontent.com/32875990/229485022-ca91c374-7776-4929-9def-9e8f75d0abb6.png">

**Comment by Vinzent03** [comment]
I'm currently hard coding some hotkeys, but will try to improve that. I don't have access to a mac, so may you please help me do debug this? 

Please run the following in the console (CTRL + SHIFT + I).
```js
 addEventListener("keydown", (e) =>
                console.log(
                    "keydown",
                    JSON.stringify({
                        key: e.key,
                        code: e.code,
                        ctrlKey: e.ctrlKey,
                        timestamp: e.timeStamp,
                        isComposing: e.isComposing,
                    })
                )
            );
            addEventListener("keyup", (e) =>
                console.log(
                    "keyup",
                    JSON.stringify({
                        key: e.key,
                        code: e.code,
                        ctrlKey: e.ctrlKey,
                        timestamp: e.timeStamp,
                        isComposing: e.isComposing,
                    })
                )
            );
```
Press `CTRL` and hold it, then press multiple times `TAB` and release `CTRL`. Just to verify, that's how you tried to use the feature, right? And share me a screenshot or the copy of the console output please.

**Comment by Vinzent03** [comment]
Thanks for helping out! Turns out the issue is not macos, but instead a change in Obsidian internal tools. I'm using non public API, which is easy to change. I'm running on a newer insider Obsidian version, which worked a bit differently than the public version. Should be fixed now.
