### ISSUE TITLE
[Feature Request] Option Exclude **Pinned Notes** from Cycle route 

### ISSUE THREAD

**Issue by FelipeRearden** [phibr0/cycle-through-panes#19]
Hello @Vinzent03 !!!!!!!!

This FR is simple to explain: it's a setting that let's the user **exclude** pinned notes that are opeend in the workspace to pass in the cycle route. 

**Example A:**

→ `Note A` is Active
→ `Note B` is Pinned
→ `Note C` is Open 

If the setting in ON the cycle commands will only cycle between `Note A` and `Note C`

**Example B:**

→ `Note A` is Open
→ `Note B` is Pinned and **Active**
→ `Note C` is Open 

If the setting in ON:
→ the cycle commands will go to `Note A` and `Note C` to to exit the pinned note 

→ then continues to cycle between only `Note A` and `Note C` 

### Why I am asking for this Feature

I am using pinned notes to store some support notes that will only be open when I need to interact with their content

📸 I even have a css snippet that make this notes **almost hidden** in the workspace:
![788DA532-C18B-4D48-A4BB-0D5F66DAF053](https://user-images.githubusercontent.com/85180696/232821778-cd95e5b1-35fa-4a1a-905e-6985d3f17ac9.jpeg)

This way I have a specific command to make this pinned note Active when need: 

As will probably know I use our beloved **Hotkeys for Specific Files** 💙💙💙 to quick switch to these pinned notes :)

---

Thanks for reading this !!!!! I hope you like my suggestion 🙏 🙏 🙏

Let me know if you need more information !!!

Have a great day 🌞

**Comment by Vinzent03** [comment]
There is now a new option in the settings to skip pinned notes.

**Comment by FelipeRearden** [comment]
> There is now a new option in the settings to skip pinned notes.

Woooowwwww !!!!! Thank you very much @Vinzent03 for this new feature :) 

I am happy that now I can implement a workflow that I have been working for the past two days !!!!!!!

I not at my vault now, this way I can test in this right now. I kindly ask for a few hours until I get home to test in my vault 

Same behavior for #18 → I wanna prepare for this test because I wanna test the new features and the new commands   with 300% of attention 💙

---

thank you very much for always making my Obsidian life better. I was checking on Discord and it almost three years since we talk for the first time. It's amazing how time flies and we are here using this amazing app ☀️ 

I get back to you soon. 

I wish you a fantastic day @Vinzent03 ☀️

**Comment by FelipeRearden** [comment]
Working perfect on version `1.2.0` . Thank you very much @Vinzent03 !!!!!!!
