### ISSUE TITLE
File extension typo?

### ISSUE THREAD

**Issue by oliverholms** [phibr0/cycle-through-panes#2]
Hi, 

Shouldn't it be `main.js` as opposed to `main.ts` as per the readme?

Plugin works as advertised with the extension changed (and with it left as is strangely?)

I am new to coding so ignore me if I am missing something obvious. 

Thank you for the plugin — I'm sure it's going to really help me.

Oliver

**Comment by phibr0** [comment]
You are right, my mistake

**Comment by phibr0** [comment]
You need to compile the .ts (Typescript) file to a .js (Javascript) File

**Comment by phibr0** [comment]
Or you download my precompiled Javascript File from the Releases Page

**Comment by phibr0** [comment]
The Readme says `main.js`

**Comment by oliverholms** [comment]
Thank you for clarifying, I was confused by the difference between the `main.js` in the readme and the `main.ts` file in the repo. I haven't used Typescript before so I didn't recognise the `.ts` extension (and when I googled it I came up with something to do with video files). 

I have downloaded the precompiled file from the Releases page and it is working as expected. Thank you.
