### ISSUE TITLE
Option to cycle between multiple tabs without switching to them

### ISSUE THREAD

**Issue by Vinzent03** [phibr0/cycle-through-panes#21]
### Discussed in https://github.com/phibr0/cycle-through-panes/discussions/20

<div type='discussions-op-text'>

<sup>Originally posted by **victorstan** May  6, 2023</sup>
I would like to request a feature that disables the tab switching when cycling. For instance, suppose you have three tabs opened, and you are currently on tab 1. When you press CTRL + TAB twice, you switch to the second tab and then to the third one.

I would like to be able to cycle between tabs without switching to them. In other words, switching should only occur when CTRL + TAB is released. This behavior is similar to the one in vscode.</div>

**Comment by lukemt** [comment]
100% agree. Please make it the default too if possible (it behaves more predictable this way, which will be good for new users)

**Comment by lukemt** [comment]
Or maybe just the default for new users, but keep the existing behaviour for existing ones idk

**Comment by BrunoRoemers** [comment]
@lukemt lucky for you I was just working on this and included your suggestion in the PR 😎

**Comment by Vinzent03** [comment]
Closed by #23
