### ISSUE TITLE
MRU cycling not working when "Show modal" option disabled

### ISSUE THREAD

**Issue by errorplane** [phibr0/cycle-through-panes#22]
Hi,
I'm finding that MRU cycling is not working when the "Show modal when switching tabs" option is disabled. 

It's not a biggie, I'm happy to have MRU at all so thanks for that!

**Comment by Vinzent03** [comment]
Works for me just fine. Are you on the latest version and may you share a screen recording?

**Comment by errorplane** [comment]
Hi,
I'm on 1.2.1 of the plugin, here's a video demo: https://youtu.be/vWH2-L0-7DE
Thanks for looking.
Daniel

**Comment by Vinzent03** [comment]
Thanks for the video! Though I still can't reproduce. You are using the "Go to previous tab" command, right? Which hotkey are you using and which OS?

**Comment by errorplane** [comment]
Aha! - That was my problem - I had the hotkeys the wrong way around - I had Ctrl+Tab linked to "Go to next tab", rather than "go to previous tab"

I've corrected it now and it works nicely either with or without the modal enabled.
![image](https://github.com/phibr0/cycle-through-panes/assets/3243209/b4e127fd-e28c-4f3c-a47d-de7ef5f96b72)

Apologies for the bother, and thanks for the plugin and the support.
