### ISSUE TITLE
Not working on mobile devices

### ISSUE THREAD

**Issue by guihasparyk** [phibr0/cycle-through-panes#26]
I've installed the plugin but it's not working, any of the commands.

Things I've tried:
- Closing and reopening vault.
- Uninstalling and reinstalling the plugin.

**Comment by Vinzent03** [comment]
Did you assign the hotkeys to the commands in the obsidian settings?

**Comment by guihasparyk** [comment]
Yes I did assign.

I was doing same tests on the Sandbox vault and I discover that it doesn't work with "Alt + Shift + Q or E or any key".
Not even "Alt + Any key".

Only worked with "Ctrl + Key". But even so I have to let to unpress a "Key" and unpress the "Ctrl" in my keyboard so that the command it's activated. If I don't let go "Ctrl" the command will not activate.

**Comment by Vinzent03** [comment]
Yeah it only works with CTRL. Are you using the modal? It currently only works with CTRL + TAB. If you disable the modal it should work with any key. You need to disable the "Focus on tabl release" setting to switch tab while still pressing ctrl.

**Comment by guihasparyk** [comment]
What do you mean by "using the modal"?

I've managed to make it work with  "Alt + Shift + Q or E or any key" on PC!

But unfortunately It is not working on mobile. Is it possible to investigate it?

**Comment by Vinzent03** [comment]
> What do you mean by "using the modal"?

There's a plugin setting to show a modal while switch tabs.

> But unfortunately It is not working on mobile. Is it possible to investigate it?

It should work just fine. Please be more specific about what doesn't work. Which device and command are you using? You are using an external keyboard, right?

**Comment by guihasparyk** [comment]
I've tried with and without modal and in all the cases is changing tabs randomly only on mobile as it's shown in this short demonstrations:

https://github.com/Vinzent03/tab-switcher/assets/50344202/0b134393-cf18-4694-bef9-d3fcbe83f650

https://github.com/Vinzent03/tab-switcher/assets/50344202/3626a20d-1ad5-4040-b962-7a746a711e01

https://github.com/Vinzent03/tab-switcher/assets/50344202/61400153-accb-4cbb-be12-d11f1bfd1eab



- **This is my plugin configuration:**


![imagem](https://github.com/Vinzent03/tab-switcher/assets/50344202/4af46e0d-aae0-4231-86a7-b3ccaf067abe)

**Comment by Vinzent03** [comment]
Ah I think I see the issue. The previous and next tab commands are designed to be used with a keyboard. The ctrl key has to be released for everything to work properly. I'm unsure if and how I want to change this.

**Comment by guihasparyk** [comment]
Alright. No problem. Thank you for clarifying it.
