### ISSUE TITLE
ctrl+Tab has no effect on macOS

### ISSUE THREAD

**Issue by mkschulze** [phibr0/cycle-through-panes#5]
Looks like I cannot get this Plugin to work with ctrl+Tab.

This does nothing on macOS Catalina. Any idea what to lok out for?

**Comment by phibr0** [comment]
You can change the Key Combination in Settings > Hotkeys.
Could you try changing it to something else?

**Comment by technicalpickles** [comment]
I ran into this too. The hotkeys to change can be found by searching "cycle through panes".

Is it possible to default these to `ctl` on macOS? If not, maybe something in the README?

**Comment by phibr0** [comment]
I will add that to the Readme now. If i have time in the next days i could look into defaulting to other keys on MacOS, i dont know when that will be though, the exam phase is starting for me.

@Vinzent03 Could you look into that?

**Comment by Vinzent03** [comment]
Could you tell me, what the default hotkey is displayed like in Obsidian? In addition, could you send your working `<vault>/.obsidian/config`file? Parts with `cycle-through-panes` would be enough. (the `modifiers` part is important).

**Comment by technicalpickles** [comment]
@phibr0  thanks! good luck on exams ✨ 

@Vinzent03 here you go:

![image](https://user-images.githubusercontent.com/159/108862025-da7fa800-75bd-11eb-8c13-dc8aba959f02.png)


```json
    "cycle-through-panes:cycle-through-panes": [
      {
        "modifiers": [
          "Ctrl"
        ],
        "key": "Tab"
      }
    ],
    "cycle-through-panes:cycle-through-panes-reverse": [
      {
        "modifiers": [
          "Ctrl",
          "Shift"
        ],
        "key": "Tab"
      }
    ]
```

**Comment by Vinzent03** [comment]
I hope the new release fixes the problem.
