### ISSUE TITLE
Option to behave like alt-tab

### ISSUE THREAD

**Issue by that0n3guy** [phibr0/cycle-through-panes#8]
Great plugin but it would be nice if there was an option for it to behave like alt-tab.  I know the functionality works like chrome, but alt tab makes more sense to me.  

I'm looking for the ability to quickly switch between the same 2 notes:

Example: I have 4 panes open.
- on pane 1
- hit ctrl-tab (keep holding ctrl) -> now on pane 2.  hit tab (since I'm still holding ctrl) -> now on pane 3
-  on pane 3
- hit ctrl-tab -> **goes back to previous pane** (pane 1)
- on pane 1
- hit ctrl-tab -> **goes back to previous pane** (pane 3)

I can quickly switch between two notes without the full cycle, or I can keep holding ctrl while taping tab to cycle.

This is how alt-tab works on windows to cycle through windows.

**Comment by Vinzent03** [comment]
Going to the last active pane is already possible with the `Focus on last active pane`. The feature with holding a key is not possible with the default Obsidian command handler, so it would need us to create our own key listener. But I don't when I have the time for this.

**Comment by that0n3guy** [comment]
> Focus on last active pane command.

I didn't know that was there... awesome.  I can work with that.   Thanks for the super fast response!

**Comment by huyz** [comment]
Now that we have Obsidian v1.0, "Focus on last active pane" works great for panes but doesn't work well for tabs.  Could it be improved?

**Comment by huyz** [comment]
Actually it doesn't work great for panes either. It seems to be work both, depending on your history.  And a bit unpredictably

**Comment by Vinzent03** [comment]
@huyz I'm wondering which specific command are you missing? I think most use cases are now implemented already in Obsidian.

**Comment by huyz** [comment]
Well, this `Focus on last active pane` should be renamed to `Focus on last active tab or pane`.  And then there should be a separate `Focus on last active pane` and `Focus on last active tab`.  All 3 are distinct features.

These are not in Obsidian, as you can see in these threads:
https://forum.obsidian.md/t/go-to-last-tab-hotkey-doesnt-work-v1-0/44888
https://forum.obsidian.md/t/option-to-cycle-through-tabs-in-recently-used-order/47891/3

**Comment by Vinzent03** [comment]
I've released a new version, with a decent rework. Please read the readme and tell if it works as expected.
